'use strict';
const $=q=>document.querySelector(q), $$=q=>document.querySelectorAll(q);
const DURATIONS={focus:25*60,short:5*60,long:50*60};
const today=()=>new Date().toLocaleDateString('en-CA');
const store={get:(key,fallback)=>{try{return JSON.parse(localStorage.getItem('qa2:'+key))??fallback}catch{return fallback}},put:(key,v)=>{try{localStorage.setItem('qa2:'+key,JSON.stringify(v))}catch{}}};
let mode='focus',remaining=DURATIONS.focus,endsAt=null,running=false,tickInterval=null,stats=store.get('stats',{date:today(),count:0,minutes:0}),tasks=store.get('tasks',[]);
if(stats.date!==today()){stats={date:today(),count:0,minutes:0};store.put('stats',stats)}
function time(v){return String(Math.floor(v/60)).padStart(2,'0')+':'+String(v%60).padStart(2,'0')}
function drawTimer(){const value=time(remaining);$('#timer').textContent=value;document.title=(running?value+' · ':'')+'Quiet Ascent — focus room'}
function updateStats(){if(stats.date!==today()){stats={date:today(),count:0,minutes:0}}$('#completed').textContent=String(stats.count).padStart(2,'0');$('#minutes').textContent=String(stats.minutes).padStart(2,'0');store.put('stats',stats)}
function finish(){running=false;clearInterval(tickInterval);tickInterval=null;remaining=0;if(mode!=='short'){stats.count+=1;stats.minutes+=Math.round(DURATIONS[mode]/60);updateStats()}$('#status').textContent='SESSION COMPLETE · WELL DONE';$('#start').innerHTML='START AGAIN <span>↗</span>';drawTimer();try{if(document.visibilityState==='visible'&&soundCtx)chime()}catch{}}
function tick(){if(!running)return;remaining=Math.max(0,Math.ceil((endsAt-Date.now())/1000));if(remaining===0){finish()}else{drawTimer()}}
function pause(){if(!running)return;tick();if(!running)return;running=false;clearInterval(tickInterval);tickInterval=null;$('#start').innerHTML='RESUME SESSION <span>↗</span>';$('#status').textContent='PAUSED'}
function start(){if(running){pause();return}if(remaining===0)remaining=DURATIONS[mode];running=true;endsAt=Date.now()+remaining*1000;tickInterval=setInterval(tick,250);$('#start').innerHTML='PAUSE SESSION <span>Ⅱ</span>';$('#status').textContent='STAY WITH YOUR ONE THING';drawTimer()}
function reset(){running=false;clearInterval(tickInterval);tickInterval=null;remaining=DURATIONS[mode];$('#start').innerHTML='BEGIN SESSION <span>↗</span>';$('#status').textContent='READY WHEN YOU ARE';drawTimer()}
$('#start').addEventListener('click',start);$('#reset').addEventListener('click',reset);$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});reset()}));
$('#intention').value=store.get('intention','');$('#intention').addEventListener('input',e=>store.put('intention',e.target.value));
function renderTasks(){const ul=$('#tasks');ul.replaceChildren();tasks.forEach(t=>{const li=document.createElement('li'),box=document.createElement('input'),label=document.createElement('label'),remove=document.createElement('button');box.type='checkbox';box.checked=!!t.done;box.setAttribute('aria-label','Mark '+t.text+' complete');box.addEventListener('change',()=>{t.done=box.checked;store.put('tasks',tasks);renderTasks()});label.textContent=t.text;remove.className='delete';remove.textContent='×';remove.setAttribute('aria-label','Remove '+t.text);remove.addEventListener('click',()=>{tasks=tasks.filter(x=>x.id!==t.id);store.put('tasks',tasks);renderTasks()});li.append(box,label,remove);ul.append(li)})}
$('#task-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#task-input'),text=input.value.trim();if(!text||tasks.length>=20)return;tasks.push({id:Date.now()+Math.random(),text,done:false});store.put('tasks',tasks);input.value='';renderTasks()});renderTasks();updateStats();drawTimer();$('#year').textContent=new Date().getFullYear();function setLocalTime(){$('#localtime').textContent=new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())};setLocalTime();setInterval(setLocalTime,20000);
let soundCtx=null,soundNode=null;
function chime(){if(!soundCtx)return;const o=soundCtx.createOscillator(),g=soundCtx.createGain();o.type='sine';o.frequency.setValueAtTime(523,soundCtx.currentTime);o.frequency.exponentialRampToValueAtTime(392,soundCtx.currentTime+.35);g.gain.setValueAtTime(.001,soundCtx.currentTime);g.gain.exponentialRampToValueAtTime(.06,soundCtx.currentTime+.05);g.gain.exponentialRampToValueAtTime(.001,soundCtx.currentTime+.8);o.connect(g).connect(soundCtx.destination);o.start();o.stop(soundCtx.currentTime+.81)}
$('#sound').addEventListener('click',async()=>{if(soundCtx){await soundCtx.close();soundCtx=null;soundNode=null;$('#sound').innerHTML='<span class="sound-icon">♫</span> SOUND OFF';$('#sound').setAttribute('aria-pressed','false');return}try{const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('unsupported');soundCtx=new C();const buff=soundCtx.createBuffer(1,soundCtx.sampleRate*2,soundCtx.sampleRate),out=buff.getChannelData(0);let b=0;for(let i=0;i<out.length;i++){const white=Math.random()*2-1;b=(b+.04*white)/1.04;out[i]=b*.25}soundNode=soundCtx.createBufferSource();soundNode.buffer=buff;soundNode.loop=true;const filter=soundCtx.createBiquadFilter(),gain=soundCtx.createGain();filter.type='lowpass';filter.frequency.value=320;gain.gain.value=.16;soundNode.connect(filter).connect(gain).connect(soundCtx.destination);soundNode.start();await soundCtx.resume();$('#sound').innerHTML='<span class="sound-icon">♫</span> SOUND ON';$('#sound').setAttribute('aria-pressed','true')}catch{if(soundCtx){soundCtx.close();soundCtx=null}$('#sound').textContent='SOUND UNAVAILABLE'}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(soundCtx)soundCtx.resume();tick()}else if(soundCtx)soundCtx.suspend()});